=== marcelopbg/DTD_parser/assets/MaoDeObra.dtd
<!ELEMENT agenciaMO (profissionais, contratos, clientes)>

<!ELEMENT profissionais (profissional+)>
<!ELEMENT contratos (contrato*)>
<!ELEMENT clientes (cliente*)>

<!ELEMENT profissional (numeroControle, nome, dataNascimento, endereco, profissao)>

<!ELEMENT numeroControle (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT dataNascimento (#PCDATA)>
<!ELEMENT endereco (#PCDATA)>
<!ELEMENT profissao (#PCDATA)>

<!ELEMENT contrato (numContrato, dataInicio, dataTermino?, valorHora, idCliente, numeroControle)>

<!ELEMENT numContrato (#PCDATA)>
<!ELEMENT dataInicio (#PCDATA)>
<!ELEMENT dataTermino (#PCDATA)>
<!ELEMENT valorHora (#PCDATA)>

<!ELEMENT cliente (idCliente, nome, endereco, cpf_cnpj)>

<!ELEMENT idCliente (#PCDATA)>
<!ELEMENT cpf_cnpj (#PCDATA)>

=== marcelopbg/DTD_parser/assets/MaoDeObra-20210427.xml
<?xml version="1.0"  encoding="UTF-8" ?>
<!DOCTYPE agenciaMO SYSTEM "MaoDeObra.dtd">
<agenciaMO>
	<profissionais>
		<profissional>
			<numeroControle></numeroControle>
			<nome></nome>
			<dataNascimento></dataNascimento>
			<endereco></endereco>
			<profissao></profissao>
		</profissional>
	</profissionais>
	<contratos>
		<contrato>
			<numContrato></numContrato>
			<dataInicio></dataInicio>
			<dataTermino></dataTermino>
			<valorHora></valorHora>
			<idCliente></idCliente>
			<numeroControle></numeroControle>
		</contrato>
	</contratos>
	<clientes>
		<cliente>
			<idCliente></idCliente>
			<nome></nome>
			<endereco></endereco>
			<cpf_cnpj></cpf_cnpj>
		</cliente>
		<cliente>
			<idCliente></idCliente>
			<nome></nome>
			<endereco></endereco>
			<cpf_cnpj></cpf_cnpj>
		</cliente>
	</clientes>
</agenciaMO>
