=== marcelopbg/DTD_parser/assets/vw.dtd
<!ELEMENT veiculos (veiculo+)>
<!ELEMENT veiculo (modelo, preço, cores, ficha-técnica, opcionais)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT preco (#PCDATA)>
<!ELEMENT cores (metalicas+,perolizadas?, solidas+)>
<!ELEMENT metalicas (cor+)>
<!ELEMENT cor (nome, preço)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT preço (#PCDATA)>
<!ELEMENT solidas (cor+)>
<!ELEMENT perolizadas (cor+)>
<!ELEMENT ficha-técnica (
                        DESEMPENHO, 
                        MOTOR, 
                        FREIOS, 
                        PRINCIPAIS-DIMENSÕES, 
                        PESOS, COMPARTIMENTO-DE-CARGA, 
                        DIREÇÃO, 
                        TRANSMISSÃO, 
                        RODAS-E-PNEUS, 
                        RESERVATÓRIO-DE-COMBUSTÍVEL, 
                        NÚMERO-MÁXIMO-DE-PASSAGEIROS
                        )>
<!ELEMENT DESEMPENHO (Aceleração-de-0-a-100-kmh, Velocidade-máxima)>
<!ELEMENT Aceleração-de-0-a-100-kmh (#PCDATA)>
<!ELEMENT Velocidade-máxima (#PCDATA)>
<!ELEMENT MOTOR (cilindrada, Potência-líquida-máxima, Torque-líquido-máximo)>
<!ELEMENT cilindrada (#PCDATA)>
<!ELEMENT Potência-líquida-máxima (#PCDATA)>
<!ELEMENT Torque-líquido-máximo (#PCDATA)>
<!ELEMENT FREIOS (Dianteiros, Traseiros)>
<!ELEMENT Dianteiros (#PCDATA)>
<!ELEMENT Traseiros (#PCDATA)>
<!ELEMENT PRINCIPAIS-DIMENSÕES (
                                Comprimento,
                                Distância-entre-eixos,
                                Largura,
                                Altura
                                )>
<!ELEMENT Comprimento (#PCDATA)>
<!ELEMENT Distância-entre-eixos (#PCDATA)>
<!ELEMENT Largura (#PCDATA)>
<!ELEMENT Altura (#PCDATA)>
<!ELEMENT PESOS (
                Em-ordem-de-marcha,
                Carga-útil-máxima?
                )>
<!ELEMENT Em-ordem-de-marcha (#PCDATA)>
<!ELEMENT Carga-útil-máxima (#PCDATA)>
<!ELEMENT COMPARTIMENTO-DE-CARGA (#PCDATA)>
<!ELEMENT DIREÇÃO (#PCDATA)>
<!ELEMENT TRANSMISSÃO (#PCDATA)>
<!ELEMENT RODAS-E-PNEUS (#PCDATA)>
<!ELEMENT RESERVATÓRIO-DE-COMBUSTÍVEL (#PCDATA)>
<!ELEMENT NÚMERO-MÁXIMO-DE-PASSAGEIROS (#PCDATA)>
<!ELEMENT opcionais (funcionais?, tecnológico?, opcional?)>
<!ELEMENT opcional (nome, preço, item+)>
<!ELEMENT tecnológico (opcional+)>
<!ELEMENT funcionais (opcional+)>
<!ELEMENT item (#PCDATA)>

=== marcelopbg/DTD_parser/assets/vw.xml
<?xml version="1.0"  encoding="UTF-8" ?>
<!DOCTYPE veiculos SYSTEM "vw.dtd">
<veiculos>
    <veiculo>
        <modelo>Gol 1.0 84 cv (E) / 75 cv (G) Manual de 5 velocidades Total flex 4 portas</modelo>
        <preço>R$ 60.260,00</preço>
        <cores>
            <metalicas>
                <cor>
                    <nome>Cinza Platinum</nome>
                    <preço>R$ 1610,00</preço>
                </cor>
                <cor>
                    <nome>Prata Sirius</nome>
                    <preço>R$ 1610,00</preço>
                </cor>
            </metalicas>
            <solidas>
                <cor>
                    <nome>Branco Cristal</nome>
                    <preço>Sem custos adicionais</preço>
                </cor>
                <cor>
                    <nome>Preto Ninja</nome>
                    <preço>Sem custos adicionais</preço>
                </cor>
                <cor>
                    <nome>Vermelho Flash</nome>
                    <preço>R$ 500,00</preço>
                </cor>
            </solidas>
        </cores>
        <ficha-técnica>
            <DESEMPENHO>
                <Aceleração-de-0-a-100-kmh>13,1 s (E) / 13,4 s (G)</Aceleração-de-0-a-100-kmh>
                <Velocidade-máxima>167 km/h (E) / 166 km/h (G)</Velocidade-máxima>
            </DESEMPENHO>
            <MOTOR>
                <cilindrada>999 cm³</cilindrada>
                <Potência-líquida-máxima>84 cv (E) / 75 cv (G) - 6.250 rpm</Potência-líquida-máxima>
                <Torque-líquido-máximo>10,4 kgfm (E) / 9,7 kgfm (G) - 3.000rpm</Torque-líquido-máximo>
            </MOTOR>
            <FREIOS>
                <Dianteiros>Discos ventilados</Dianteiros>
                <Traseiros>Tambor</Traseiros>
            </FREIOS>
            <PRINCIPAIS-DIMENSÕES>
                <Comprimento>3.892 mm</Comprimento>
                <Distância-entre-eixos>2.467 mm</Distância-entre-eixos>
                <Largura>1.893 mm</Largura>
                <Altura>1.475 mm</Altura>
            </PRINCIPAIS-DIMENSÕES>
            <PESOS>
                <Em-ordem-de-marcha>1.001 kg</Em-ordem-de-marcha>
                <Carga-útil-máxima>434 kg</Carga-útil-máxima>
            </PESOS>
            <COMPARTIMENTO-DE-CARGA>263 l</COMPARTIMENTO-DE-CARGA>
            <DIREÇÃO>Hidráulica</DIREÇÃO>
            <TRANSMISSÃO>Manual de 5 velocidades</TRANSMISSÃO>
            <RODAS-E-PNEUS>
                185/65 R14
            </RODAS-E-PNEUS>
            <RESERVATÓRIO-DE-COMBUSTÍVEL>55 litros</RESERVATÓRIO-DE-COMBUSTÍVEL>
            <NÚMERO-MÁXIMO-DE-PASSAGEIROS>5</NÚMERO-MÁXIMO-DE-PASSAGEIROS>
        </ficha-técnica>
        <opcionais>
            <funcionais>
                <opcional>
                    <nome>Urban Completo</nome>
                    <preço>R$ 6.620,00</preço>
                    <item>"I-System com Eco-Comfort" - computador de bordo</item>
                    <item>"Keyless" - sistema de alarme com comando remoto</item>
                    <item>2 Luzes de leitura dianteiras e 2 luzes de leitura traseiras</item>
                    <item>4 alto-falantes e 2 tweeters</item>
                    <item>Alças de segurança no teto</item>
                    <item>Chave tipo "canivete" com controle remoto</item>
                    <item>Coluna de direção com ajuste de altura e profundidade</item>
                    <item>Destravamento elétrico da tampa traseisa com controle remoto</item>
                    <item>Espelhos retrovisores e maçanetas das portas na cor do veículo</item>
                    <item>Espelhos retrovisores externos com ajustes elétricos e função tilt-down no lado do passageiro</item>
                    <item>Espelhos retrovisores externos com luzes indicadoras de direção integradas</item>
                    <item>Faróis de neblina</item>
                    <item>Lanternas traseiras escurecidas</item>
                    <item>Para-sol com espelho iluminado para motorista</item>
                    <item>Para-sol com espelho iluminado para passageiro</item>
                    <item>Pneus 195/55 R15</item>
                    <item>Rodas de liga leve 15"</item>
                    <item>Sensor de estacionamento traseiro</item>
                    <item>Sistema de som touchscreen "Composition Touch" com APP-Connect</item>
                    <item>Travamento elétrico das portas com controle remoto</item>
                    <item>Vidros elétricos dianteiros e traseiros</item>
                    <item>Volante multifuncional com comando do sistema de som e "I-System"</item>
                </opcional>
            </funcionais>
            <tecnológico>
                <opcional>
                    <nome>Interatividade Media Plus</nome>
                    <preço>R$ 1.300,00</preço>
                    <item>4 alto-falantes e 2 tweeters</item>
                    <item>Sistema infotainment "Media Plus" com bluetooth, MP3 e entradas USB, SD-card e AUX-IN</item>
                </opcional>
            </tecnológico>
        </opcionais>
    </veiculo>
    <veiculo>
        <modelo>Voyage 1.0 84 cv (E) / 75 cv (G) Manual de 5 velocidades Total flex 4 portas</modelo>
        <preço>R$ 71.350,00</preço>
        <cores>
            <metalicas>
                <cor>
                    <nome>Cinza Platinum</nome>
                    <preço>R$ 1610,00</preço>
                </cor>
                <cor>
                    <nome>Prata Sirius</nome>
                    <preço>R$ 1610,00</preço>
                </cor>
            </metalicas>
            <solidas>
                <cor>
                    <nome>Branco Cristal</nome>
                    <preço>Sem custos adicionais</preço>
                </cor>
                <cor>
                    <nome>Preto Ninja</nome>
                    <preço>Sem custos adicionais</preço>
                </cor>
                <cor>
                    <nome>Vermelho Flash</nome>
                    <preço>R$ 500,00</preço>
                </cor>
            </solidas>

        </cores>
        <ficha-técnica>
            <DESEMPENHO>
                <Aceleração-de-0-a-100-kmh>13,2 s (E) / 13,4 s (G)</Aceleração-de-0-a-100-kmh>
                <Velocidade-máxima>173 km/h (E) / 171 km/h (G)</Velocidade-máxima>
            </DESEMPENHO>
            <MOTOR>
                <cilindrada>999 cm³</cilindrada>
                <Potência-líquida-máxima>84 cv (E) / 75 cv (G) - 6.250 rpm</Potência-líquida-máxima>
                <Torque-líquido-máximo>10,4 kgfm (E) / 9,7 kgfm (G) - 3.000rpm</Torque-líquido-máximo>
            </MOTOR>
            <FREIOS>
                <Dianteiros>Discos ventilados</Dianteiros>
                <Traseiros>Tambor</Traseiros>
            </FREIOS>
            <PRINCIPAIS-DIMENSÕES>
                <Comprimento>4213 mm</Comprimento>
                <Distância-entre-eixos>2.467 mm</Distância-entre-eixos>
                <Largura>1.893 mm</Largura>
                <Altura>1.463 mm</Altura>
            </PRINCIPAIS-DIMENSÕES>
            <PESOS>
                <Em-ordem-de-marcha>1.015 kg</Em-ordem-de-marcha>
                <Carga-útil-máxima>439 kg</Carga-útil-máxima>
            </PESOS>
            <COMPARTIMENTO-DE-CARGA>462 l</COMPARTIMENTO-DE-CARGA>
            <DIREÇÃO>Hidráulica</DIREÇÃO>
            <TRANSMISSÃO>Manual de 5 velocidades</TRANSMISSÃO>
            <RODAS-E-PNEUS>
                185/65 R14
            </RODAS-E-PNEUS>
            <RESERVATÓRIO-DE-COMBUSTÍVEL>55 litros</RESERVATÓRIO-DE-COMBUSTÍVEL>
            <NÚMERO-MÁXIMO-DE-PASSAGEIROS>5</NÚMERO-MÁXIMO-DE-PASSAGEIROS>
        </ficha-técnica>
        <opcionais>
            <funcionais>
                <opcional>
                    <nome>Urban Completo</nome>
                    <preço>R$ 6.620,00</preço>
                    <item>"I-System com Eco-Comfort" - computador de bordo</item>
                    <item>"Keyless" - sistema de alarme com comando remoto</item>
                    <item>2 Luzes de leitura dianteiras e 2 luzes de leitura traseiras</item>
                    <item>4 alto-falantes e 2 tweeters</item>
                    <item>Alças de segurança no teto</item>
                    <item>Chave tipo "canivete" com controle remoto</item>
                    <item>Coluna de direção com ajuste de altura e profundidade</item>
                    <item>Destravamento elétrico da tampa traseisa com controle remoto</item>
                    <item>Espelhos retrovisores e maçanetas das portas na cor do veículo</item>
                    <item>Espelhos retrovisores externos com ajustes elétricos e função tilt-down no lado do passageiro</item>
                    <item>Espelhos retrovisores externos com luzes indicadoras de direção integradas</item>
                    <item>Faróis de neblina</item>
                    <item>Lanternas traseiras escurecidas</item>
                    <item>Para-sol com espelho iluminado para motorista</item>
                    <item>Para-sol com espelho iluminado para passageiro</item>
                    <item>Pneus 195/55 R15</item>
                    <item>Rodas de liga leve 15"</item>
                    <item>Sensor de estacionamento traseiro</item>
                    <item>Sistema de som touchscreen "Composition Touch" com APP-Connect</item>
                    <item>Travamento elétrico das portas com controle remoto</item>
                    <item>Vidros elétricos dianteiros e traseiros</item>
                    <item>Volante multifuncional com comando do sistema de som e "I-System"</item>
                </opcional>
            </funcionais>
            <tecnológico>
                <opcional>
                    <nome>Interatividade Media Plus</nome>
                    <preço>R$ 1.300,00</preço>
                    <item>4 alto-falantes e 2 tweeters</item>
                    <item>Sistema infotainment "Media Plus" com bluetooth, MP3 e entradas USB, SD-card e AUX-IN</item>
